### ISSUE TITLE
Repeaters support and PHP 8.1

### ISSUE THREAD

**Issue by matjazpotocnik** [kixe/ProcessPolls#1]
Hi Christoph! Testing this module and found this:

`ProcessWire: ProcessPolls: You must set a 'page' (type Page) property to InputfieldRepeater with repeater field 'fieldsetpage'.`

I think no one will ever use repeaters for polls/elections, but nevertheless, I wanted to let you know.

There are some deprecation warnings in PHP8:

`PHP Deprecated: Function strftime() is deprecated in ...\site\modules\ProcessPolls-main\ProcessPolls.module:472 and 473`

**Comment by kixe** [comment]
> `ProcessWire: ProcessPolls: You must set a 'page' (type Page) property to InputfieldRepeater with repeater field 'fieldsetpage'.`
> 
> I think no one will ever use repeaters for polls/elections, but nevertheless, I wanted to let you know.

_short answer_
You have a repeater field in the template that you want to use for the poll. If you don't want to use this field for your poll,  remove it.

_long answer_
This error was generated by **FormProcessor** which is required by **ProcessPolls**. I've released an update for **FormProcessor** so that fields that need a page assigned are ignored if the page doesn't exist or hasn't already been created.

---

> PHP Deprecated: Function strftime() is deprecated in ...\site\modules\ProcessPolls-main\ProcessPolls.module:472 and 473

thanks, fixed!
